### PR TITLE
Update pyproj to 3.3+ and datum grids for Europe and North America

### LINKED ISSUE #25: Upgrade to PROJ 8.2.0
There's a new PROJ release out, WEBPROJ should use it once it has had its first maintenance release. Adopting the new version should be simple but there may be a few issues regarding grids that may need to be handled differently. 

When building the docker image grids can now be pulled from `https://cdn.proj.org/` which should speed things up a bit.

### LINKED ISSUE #33: Switch to Proj CDN
We currently download datum grids from the somewhat slow OSGeo server. The Proj CDN should work better, so we ought to switch over to using that.

### PR DESCRIPTION
**Pull request by larsnaesbye**
Fixes #25 
Fixes #33

### CODE REVIEW

**Review by kbevers — CHANGES_REQUESTED** [review]
Get the grids from cdn.proj.org as demonstrated in #25. Using `projsync` is the ideal way to do it, as it will ensure the most recent versions are grabbed without the need for specifying version numbers. If `projsync` is not available when building the Dockerfile links to specific grids from the CDN is the next best thing. From memory we need the DVR90, DNN, GVR2000 and GVR2016 grids as well as the various `dk_sdfe_*.pol` files.

I'd like to see the pyproj version pinned in the Docker file. It believe it is possible to do something like `pip install 'pyproj>=3.3.0'`.

The conda changes looks good.

**Comment by kbevers** [comment]
Oh yeah, just for reference, the proj-datumgrid packages are [deprecated](https://proj.org/download.html) since PROJ 7 so we really shouldn't use them. The CDN via projsync is the best option. There is also the proj-data package but that is a big whopper at 1+ GB and a shit ton of grids we don't need here. That should bring you more or less up to speed on the PROJ grid situation :-)

**Comment by larsnaesbye** [comment]
I was just going to mention the `proj-data` package - I just discovered it too :)

**Review by kbevers — APPROVED** [review]
Looks good. Unfortunately we have no way of knowing if it actually works or not since Travis has stopped working (see https://github.com/Kortforsyningen/WEBPROJ/issues/34)

**Pull request merged**
